// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dd6088f5-e089-4fca-a1ee-1cb52b5fe32b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_IKj7S2Edv",
    "aws_user_pools_web_client_id": "172dlg8tgv95gva3ca0g1ukfn6",
    "aws_mobile_analytics_app_id": "70a392f5aa6c461da14e6bd4fdef3535",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://ahjny5xdnvfvtlhzurvrejjfua.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
