// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dd6088f5-e089-4fca-a1ee-1cb52b5fe32b",
    "aws_cognito_region": "us-west-2",
    "aws_mobile_analytics_app_id": "70a392f5aa6c461da14e6bd4fdef3535",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
